---
name: "Infinitude"
description: Run Infinitude by nebulous as a Home Assistant Addon.
version: "v2024.04.23.24"
slug: "infinitude"
init: true
arch:
  - aarch64
  - amd64
  - armv7
  - i386
options:
  app_secret: Pogotudinal
  mode: Production
  pass_reqs: 1020
  serial_tty: ""
  serial_socket: ""
schema:
  mode: list(Development|Production)
  app_secret: str
  pass_reqs: int(0,)
  serial_tty: str?
  serial_socket: str?
ports:
  3000/tcp: 34500
ports_description:
  3000/tcp: Port to expose infinitude's web server on.
watchdog: http://[HOST]:[PORT:3000]/api/status
panel_icon: mdi:sun-snowflake-variant
stage: stable
image: ghcr.io/sosheskaz/infinitude-ha-addon
