name: Perform a release

on: [workflow_dispatch]  # yamllint disable-line rule:truthy
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - id: version
        name: Get version string
        run: echo "::set-output name=VERSION::v$(date +'+%Y.%m.%d').${{ github.run_number }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true
