name: Test image build

on: [push]  # yamllint disable-line rule:truthy
jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./Store"
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Build Inventory Image"
        run: |
          docker buildx bake ci
