---
name: Perform a release

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - &base auto-promote

jobs:
  update-infinitude:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mikefarah/yq@v4

      - name: Get experimental version
        id: experimental_version
        run: |
          VERSION="$(yq e -i '.version = "${{ needs.metadata.outputs.VERSION }}"' infinitude-experimental/config.yaml)"
          echo "EXPERIMENTAL_VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Update the stable version
        run: |
          yq e -i '.version = "${{ needs.metadata.outputs.VERSION }}"' infinitude/config.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # use the output from the previous task
          commit-message: Promote infinitude ${{ steps.experimental_version.outputs.EXPERIMENTAL_VERSION }}
          title: Promote infinitude ${{ needs.metadata.outputs.VERSION }}
          body: |
            Update Infinitude to ${{ needs.metadata.outputs.VERSION }}
          branch: promote-experimental-to-stable
          delete-branch: true
          base: *base
          reviewers: sosheskaz
          assignees: sosheskaz
