---
name: Promote Experimental to Stable

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - auto-promote

jobs:
  update-infinitude:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mikefarah/yq@v4

      - name: Get experimental version
        id: experimental_version
        run: |
          VERSION="$(yq e .version infinitude-experimental/config.yaml)"
          IMAGE="$(yq e .image infinitude-experimental/config.yaml)"
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "IMAGE=${IMAGE}" >> $GITHUB_OUTPUT

      - name: Update the stable version
        run: |
          yq e -i '.version = "${{ needs.metadata.outputs.VERSION }}"' infinitude/config.yaml
          yq e -i '.image = "${{ steps.experimental_version.outputs.IMAGE }}"' infinitude/config.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # use the output from the previous task
          commit-message: Promote infinitude ${{ steps.experimental_version.outputs.EXPERIMENTAL_VERSION }}
          title: Promote infinitude ${{ needs.metadata.outputs.VERSION }}
          body: |
            Update Infinitude to ${{ needs.metadata.outputs.VERSION }}
          branch: promote-experimental-to-stable
          delete-branch: true
          base: auto-promote
          reviewers: sosheskaz
          assignees: sosheskaz
